### ISSUE TITLE
can_dbc_parser is not raptor specific.

### ISSUE THREAD

**Issue by Timple** [NewEagleRaptor/raptor-dbw-ros2#6]
We happily use the `can_dbc_parser` in ROS1. I noticed in ROS2 the name changed with a `raptor_` prefix.

Unlike the other packages in the repo, this one is not raptor specific. So maybe the name `can_dbc_parser` might be enough.

If you decide to leave the prefix that's okay of course. We can make the dependency name conditional :+1:  

_edit: released already_

**Comment by NewEagleRaptor** [comment]
OK, we can revert that change 👍

**Comment by NewEagleRaptor** [comment]
The package name is reverted in GitHub now, & I'm working on putting a bloom-release together that should be finished in a couple days. This change will be included in that release.

**Comment by NewEagleRaptor** [comment]
For foxy, please see tag foxy-1.1.0
Bloom-release for foxy-1.1.0 has been merged to rosdistro; please see https://github.com/ros/rosdistro/pull/29891
For dashing, please see tag dashing-1.1.0; dashing cannot be bloom-released (support ended in May 2021)
