### ISSUE TITLE
Is it possible to use this repo without a DBC file?

### ISSUE THREAD

**Issue by sisaha9** [NewEagleRaptor/raptor-dbw-ros2#8]
We have a simulink model but have some issues generating a DBC file. Is it possible to send RAW CAN messages and have it read from this repo?

**Comment by NewEagleRaptor** [comment]
Our DBW ROS node already contains a DBC & is built around it; that is the DBC you should be using with this repo. Are you having trouble using our DBC?

You could definitely send raw CAN to our ROS node, as long as you followed our included DBC.

[New_Eagle_DBW_3.3.542.dbc](https://github.com/NewEagleRaptor/raptor-dbw-ros2/blob/foxy/raptor_dbw_can/launch/New_Eagle_DBW_3.3.542.dbc)

**Comment by sisaha9** [comment]
Got it. In that case if we do end up using a new DBC would we have to rewrite certain parts of the repository?

**Comment by NewEagleRaptor** [comment]
Correct.  If you’d like help, please contact [sales@neweagle.net](mailto:sales@neweagle.net).
