### ISSUE TITLE
ROS2 Galactic / Rolling release

### ISSUE THREAD

**Issue by pjreed** [NewEagleRaptor/raptor-dbw-ros2#9]
Would it be possible to get a release of this repository into the ROS2 Galactic & Rolling distributions?  Thanks!

**Comment by NewEagleRaptor** [comment]
Thanks for reaching out.  It is not yet in our plan, but we are evaluating. Feel free to reach out to [sales@neweagle.net](mailto:sales@neweagle.net) if you need anything else.
